# Generated by Django 5.2 on 2025-05-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindt',
            name='admin_id',
            field=models.CharField(blank=True, default='6834bdca', max_length=8, unique=True),
        ),
    ]
