# Generated by Django 5.2 on 2025-05-28 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.CharField(blank=True, max_length=500, null=True)),
                ('user_uid', models.CharField(blank=True, max_length=550, null=True)),
                ('sku_code', models.CharField(blank=True, max_length=550, null=True)),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('color', models.CharField(blank=True, max_length=550, null=True)),
                ('img1', models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/')),
                ('size', models.CharField(blank=True, max_length=330, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('mrp', models.IntegerField(blank=True, null=True)),
                ('delivery_charges', models.CharField(blank=True, max_length=30, null=True)),
                ('discount', models.CharField(blank=True, max_length=530, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=530, null=True)),
                ('total_qty', models.CharField(blank=True, max_length=530, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Category/')),
            ],
        ),
        migrations.CreateModel(
            name='Ecommerc_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(default='9bf0449e', max_length=8, unique=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=255)),
                ('verify_code', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.CharField(blank=True, max_length=550, null=True)),
                ('user_uid', models.CharField(blank=True, max_length=550, null=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=500, null=True)),
                ('street1', models.CharField(blank=True, max_length=500, null=True)),
                ('street2', models.CharField(blank=True, max_length=500, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, default='India', max_length=500, null=True)),
                ('region', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('order_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('tracking_link', models.CharField(blank=True, max_length=100, null=True)),
                ('order_status', models.CharField(blank=True, choices=[('Pending Orders', 'Pending Orders'), ('New Orders', 'New Orders'), ('Ready Orders', 'Ready Orders'), ('Shipped Orders', 'Shipped Orders'), ('Delivered Orders', 'Delivered Orders'), ('Cancelled Orders', 'Cancelled Orders'), ('Failed Orders', 'Failed Orders')], default='New Orders', max_length=50, null=True)),
                ('order_type', models.CharField(blank=True, choices=[('COD', 'COD'), ('Prepaid', 'Prepaid')], default='COD', max_length=50, null=True)),
                ('sku_code', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('qty', models.CharField(blank=True, max_length=300, null=True)),
                ('img1', models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='SubCategory/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecommerce.category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sku_code', models.CharField(blank=True, max_length=500, null=True)),
                ('brand', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('mrp', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image1', models.ImageField(upload_to='product_images/')),
                ('image2', models.ImageField(upload_to='product_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_bestselling', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.category')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.subcategory')),
            ],
        ),
    ]
