# Generated by Django 5.2 on 2025-05-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerc_user',
            name='user_uid',
            field=models.CharField(default='16a635e0', max_length=8, unique=True),
        ),
    ]
